name       : kdevelop-pg-qt
version    : 2.1.0
release    : 2
source     :
    - https://cdn.download.kde.org/stable/kdevelop-pg-qt/2.1.0/src/kdevelop-pg-qt-2.1.0.tar.xz : 20d84d25bd40610bd6c0964e4fe0642e56c41b76a65575122dc5196649621e5d
license    : LGPL-2.1
component  : programming
summary    : Parser generator written in readable source-code
description: |
    KDevelop-PG-Qt is a parser generator written in readable source-code and generating readable source-code. Its syntax was inspirated by AntLR. It implements the visitor-pattern and uses the Qt library.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
