name       : kdevelop-pg-qt
version    : 2.0
release    : 1
source     :
    - https://download.kde.org/stable/kdevelop-pg-qt/2.0.0/src/kdevelop-pg-qt-2.0.tar.xz : 2f778d324b7c0962e8bb5f62dd2643bac1a6f3ac971d145b6aace7cd61878993
license    : LGPL-2.1
component  : programming
summary    : Parser generator written in readable source-code
description: |
    KDevelop-PG-Qt is a parser generator written in readable source-code and generating readable source-code. Its syntax was inspirated by AntLR. It implements the visitor-pattern and uses the Qt library.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
