name       : kdevelop-pg-qt
version    : 2.2.0
release    : 3
source     :
    - https://download.kde.org/stable/kdevelop-pg-qt/2.2.0/src/kdevelop-pg-qt-2.2.0.tar.xz : 0777689605e5133754f116c991741f725802f18fc4215a5ccbf4230751f24405
license    : LGPL-2.1
component  : programming
summary    : Parser generator written in readable source-code
description: |
    KDevelop-PG-Qt is a parser generator written in readable source-code and generating readable source-code. Its syntax was inspirated by AntLR. It implements the visitor-pattern and uses the Qt library.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
