name       : kdevelop-pg-qt
version    : 2.2.1
release    : 5
source     :
    - https://download.kde.org/stable/kdevelop-pg-qt/2.2.1/src/kdevelop-pg-qt-2.2.1.tar.xz : c13931788ac9dc02188cdd9c6e71e164ae81b4568b048748652bbf6fa4a9c62b
license    : LGPL-2.1
component  : programming
summary    : Parser generator written in readable source-code
description: |
    KDevelop-PG-Qt is a parser generator written in readable source-code and generating readable source-code. Its syntax was inspirated by AntLR. It implements the visitor-pattern and uses the Qt library.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
